# Generated by Django 4.2 on 2023-04-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name_plural": "products"},
        ),
        migrations.AlterModelOptions(
            name="sales",
            options={"verbose_name_plural": "sales"},
        ),
        migrations.AlterModelOptions(
            name="size",
            options={"verbose_name_plural": "sizes"},
        ),
        migrations.AlterModelOptions(
            name="type",
            options={"verbose_name_plural": "types"},
        ),
        migrations.RemoveField(
            model_name="size",
            name="code",
        ),
        migrations.AddField(
            model_name="type",
            name="code",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
    ]
